### ISSUE TITLE
./build.sh 编译失败，报错

### ISSUE THREAD

**Issue by Hary1026** [AimRT/AimRT#119]
**Version of AimRT**
main最新源码

versions of gcc, cmake, python etc.
gcc version: 11.4.0
cmake version: 3.31.1
python version: 3.10.12
ubuntu version:  Ubuntu 22.04.5 LTS
内核版本： 5.15.136-tegra

**Describe the bug**
./build.sh 编译报错： 
[ 55%] Building CXX object src/protocols/plugins/ros2_plugin_proto/CMakeFiles/ros2_plugin_proto__rosidl_typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/ros2_plugin_proto/srv/detail/ros_rpc_wrapper__type_support.cpp.o
running egg_info
creating ros2_plugin_proto.egg-info
writing ros2_plugin_proto.egg-info/PKG-INFO
writing dependency_links to ros2_plugin_proto.egg-info/dependency_links.txt
writing top-level names to ros2_plugin_proto.egg-info/top_level.txt
writing manifest file 'ros2_plugin_proto.egg-info/SOURCES.txt'
reading manifest file 'ros2_plugin_proto.egg-info/SOURCES.txt'
writing manifest file 'ros2_plugin_proto.egg-info/SOURCES.txt'
[ 55%] Linking CXX shared library ../../../../libros2_plugin_proto__rosidl_typesupport_introspection_cpp.so
make[3]: *** read jobs pipe: Bad file descriptor.  Stop.
make[3]: *** Waiting for unfinished jobs....
[ 55%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/global.cc.o
[ 55%] Built target ament_cmake_python_build_ros2_plugin_proto_egg
[ 55%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/http/http_channel_backend.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [src/runtime/python_runtime/CMakeFiles/aimrt_runtime_python_runtime.dir/build.make:79: src/runtime/python_runtime/CMakeFiles/aimrt_runtime_python_runtime.dir/python_runtime_main.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:8076: src/runtime/python_runtime/CMakeFiles/aimrt_runtime_python_runtime.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 55%] Built target ros2_plugin_proto__rosidl_typesupport_introspection_cpp
[ 55%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/http/http_rpc_backend.cc.o
[ 55%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/net_plugin.cc.o
[ 56%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/net_plugin_main.cc.o
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
[ 56%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/tcp/tcp_channel_backend.cc.o
gmake[2]: *** [src/runtime/python_runtime/CMakeFiles/aimrt_runtime_python_runtime_ros2.dir/build.make:175: aimrt_python_runtime_ros2.cpython-310-aarch64-linux-gnu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:8111: src/runtime/python_runtime/CMakeFiles/aimrt_runtime_python_runtime_ros2.dir/all] Error 2
[ 56%] Building CXX object src/plugins/net_plugin/CMakeFiles/aimrt_plugins_net_plugin.dir/udp/udp_channel_backend.cc.o
[ 56%] Linking CXX shared library ../../../libaimrt_net_plugin.so
[ 56%] Built target aimrt_plugins_net_plugin
165354 INFO: Building PKG (CArchive) aimrt_cli.pkg completed successfully.
165402 INFO: Bootloader /home/ubuntu/.local/lib/python3.10/site-packages/PyInstaller/bootloader/Linux-64bit-arm/run
165402 INFO: checking EXE
165417 INFO: Building because python_lib changed
165418 INFO: Building EXE from EXE-00.toc
165420 INFO: Copying bootloader EXE to /home/ubuntu/Desktop/jinrong/AimRT/src/tools/aimrt_cli/dist/aimrt_cli
165425 INFO: Appending PKG archive to custom ELF section in EXE
167005 INFO: Building EXE from EXE-00.toc completed successfully.
[ 56%] Built target aimrt_cli
gmake: *** [Makefile:166: all] Error 2

**To Reproduce**
1. 我们是在JetRover的一款智能车自带的ubuntu系统上项部署AimRT
2. 下载最新源码后，执行./build.sh 编译到中间的时候报上面的错误

麻烦看下是什么原因导致上面的编译错误，应该怎么解决呢？

**Comment by zhangyi1357** [comment]
根据这个来看是系统资源不足导致杀死了编译进程，将 build.sh 中的核数调小即可。

```
cmake --build build --config Release --target install --parallel $(nproc)
```

-->

```
cmake --build build --config Release --target install --parallel 2
```
