### ISSUE TITLE
[Bug] Windows环境下 源码引入AimRT的小问题 

### ISSUE THREAD

**Issue by livestronglxr** [AimRT/AimRT#17]
1.       
    AimRT工程根目录的CMakeLists.txt中，决定AIMRT_MASTER_PROJECT标志开关的条件是：`if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR) `。
从而导致了以源码引入AimRT时，该条件不满足，未能正确添加相关配置，从而导致编译不过。
2.
    Windows环境下，开启gRPC插件开关，grpc plugin库编译不过。
    需要添加add_definitions(-D ssize_t=long)

**Comment by AimRT** [comment]
您好，感谢您的宝贵反馈，目前问题已经在着手排查，windows 环境下较为缺少实际使用的测试，可能会有一些未知的问题。
