### ISSUE TITLE
About ros2-humble

### ISSUE THREAD

**Issue by acuteyaya** [AimRT/AimRT#50]
When I constructed my project using GetAimRT.cmake, ros2 couldn't find the message type for the back-end node of ros2_plugin, and native ros2 couldn't subscribe to topics using the same type.and install/share is not found in the build folder
![1](https://github.com/user-attachments/assets/c4c0d81b-d37e-44e3-bcb7-21cdce142028)

**Comment by zhangyi1357** [comment]
The `install/share` directory is likely missing because the `make install` step wasn't executed.

针对自定义的消息类型，需要运行相应消息类型的 setup 脚本，例如https://github.com/AimRT/AimRT/blob/cb01a34047c52a45708fc872c5fa40adad575dd9/src/examples/plugins/ros2_plugin/install/linux/bin/start_examples_plugins_ros2_plugin_ros2_chn_pub.sh#L5

**Comment by shengqihailuo1** [comment]
I have a camera driver that publishes a native ros2 topic, can I subscribe to this topic and forward camera data to a remote server via rpc? Is it modified with the case of "native ros2 client calls aimrt server"?
https://github.com/AimRT/AimRT/tree/main/src/examples/plugins/ros2_plugin

**Comment by zhangyi1357** [comment]
> I have a camera driver that publishes a native ros2 topic, can I subscribe to this topic and forward camera data to a remote server via rpc? Is it modified with the case of "native ros2 client calls aimrt server"?https://github.com/AimRT/AimRT/tree/main/src/examples/plugins/ros2_plugin

Q1: Yes
Q2: This is also feasible, but note that the AimRT service name has a specific format {proto_type}:/{ServiceName}/{FunctionName}, and will be rewritten to some extent (due to some special characters). Therefore, you need to run `ros2 service list` to see the correct service name.
