### ISSUE TITLE
Proposal: Add a script to check system environment requirements

### ISSUE THREAD

**Issue by ChuheZhang** [AimRT/AimRT#75]
I would like to propose adding a script that checks whether the system environment meets the requirements for building and running the project.

**Details**

The script performs the following tasks:

- Checks for required tools and libraries such as CMake, GCC, G++, Python, and optional dependencies like ROS2, Rust, and OpenSSL.
- Verifies that the installed versions meet the minimum requirements.
- Generates appropriate CMake build commands based on the detected environment.
- Adjusts build options to disable features that are missing dependencies, preventing build errors.
- Provides color-coded output (green, yellow, red) to indicate the status of each configuration check.

**Benefits**

- Helps users quickly identify missing dependencies or configurations.
- Improves the build experience by providing tailored build commands.
- Reduces the likelihood of build failures due to missing or incompatible dependencies.

**Implementation**

I have already written the script and can submit it in a pull request.

**Additional Information**

- The script is named `check_aimrt_env.sh`.
- It integrates content from `test.sh` to include test steps.

**Comment by AimRT** [comment]
Closed as discussed in https://github.com/AimRT/AimRT/pull/76#issuecomment-2456283246.
